### ISSUE TITLE
ImportError: cannot import name 'cmudict'

### ISSUE THREAD

**Issue by hylee-250** [SMART-TTS/SMART-Single_Emotional_TTS#4]
안녕하세요 Pre-trained model을 통해서 inference 결과를 확인해보고 싶어서 코드를 돌려보았지만
text 폴더 내에 cmudict가 존재하지 않아서 오류가 뜨는데 이 부분은 어떻게 해결을 해야할지 문의드립니다.

Traceback (most recent call last):
  File "synthesis.py", line 1, in <module>
    from preprocess import get_dataset, DataLoader, collate_fn_transformer
  File "/workspace/SMART-Single_Emotional_TTS/preprocess.py", line 7, in <module>
    from text.HangulUtilsHrim import hangul_to_sequence
  File "/workspace/SMART-Single_Emotional_TTS/text/__init__.py", line 5, in <module>
    from text.symbols import symbols
  File "/workspace/SMART-Single_Emotional_TTS/text/symbols.py", line 10, in <module>
    from text import cmudict
ImportError: cannot import name 'cmudict'

**Comment by Rulunation** [comment]
안녕하세요, 본 코드는 한국어 합성기이기 때문에 cmudict가 필요 없습니다. 예전 코드에서 미처 코멘트처리 못하여 발생한 에러이며, symbols.py 에서 해당 줄을 코멘트 처리 하시고 사용해 보시기 바랍니다.
